services:
  tidb:
    image: pingcap/tidb:v7.5.1
    container_name: timer-service-tidb-dev
    ports:
      - "4000:4000"
    command: >
      /tidb-server
      --store=unistore
      --path=""
      --advertise-address=tidb
    networks:
      - timer-network
    environment:
      - TIDB_VERSION=v7.5.1

  tidb-init: # TODO This doesn't work....
    image: pingcap/tidb:v7.5.1
    depends_on:
      - tidb
    volumes:
      - ../server/databases/mysql/schema:/schema
    networks:
      - timer-network
    entrypoint: >
      sh -c "
        echo 'Waiting for TiDB to be ready...' &&
        until mysqladmin ping -h mysql -u timer_user -ptimer_password --silent; do
          echo 'MySQL not ready, waiting...'
          sleep 2
        done &&
        echo 'Executing schema...' &&
        mysql -h mysql -u timer_user -ptimer_password timer_service < /schema/v1.sql &&
        echo 'Schema execution completed successfully!'
      "

networks:
  timer-network:
    driver: bridge 