/*
 * Distributed Durable Timer Service API
 *
 * A distributed, durable timer service that can schedule and execute HTTP webhook callbacks  at specified times with high reliability and scalability.  ## Features - Create one-time timers with custom payloads - Durable persistence across service restarts - At-least-once delivery semantics - Configurable retry policies and timeouts - Timer modification and cancellation - Callback response can update timer schedule
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package genapi

type RetryPolicy struct {

	// Maximum number of retry attempts
	MaxRetries int32 `json:"maxRetries,omitempty"`

	// the total duration of retry attempts
	MaxRetryAttemptsDuration string `json:"maxRetryAttemptsDuration,omitempty"`

	// Initial retry interval (e.g., \"30s\", \"1m\")
	InitialInterval string `json:"initialInterval,omitempty"`

	// Multiplier for exponential backoff
	BackoffMultiplier float32 `json:"backoffMultiplier,omitempty"`

	// Maximum retry interval
	MaxInterval string `json:"maxInterval,omitempty"`
}
